export const VIDEO_ACTIONS = {
    "ADD_VIDEO_NUMBER":"ADD_VIDEO_NUMBER",
    "ADD_TITLE":"ADD_TITLE",
    "ADD_COURSE_ID":"ADD_COURSE_ID",
    "ADD_SECTION":"ADD_SECTION",
    "ADD_DESCRIPTION":"ADD_DESCRIPTION",
    "ADD_COURSES":"ADD_COURSES",
    "ADD_SECTION_ID":"ADD_SECTION_ID",
    "CHANGE_IS_VIDEO_CHOOSE":"CHANGE_IS_VIDEO_CHOOSE",
    "CHANGE_IS_FREE":"CHANGE_IS_FREE",
}