const actionTypes = {
    UPDATE_TITLE:"UPDATE_TITLE",
    SET_ERROR:"SET_ERROR",
    DELETE_ERROR:"DELETE_ERROR",
    DELETE_SECTION:"DELETE_SECTION",
    UPDATE_DESCRIPTION:"UPDATE_DESCRIPTION",
    ADD_SECTION:"ADD_SECTION",
    SET_LEVEL:"SET_LEVEL",
    SET_MASTER:"SET_MASTER",
    SET_CATEGORY:"SET_CATEGORY",
    SET_IS_FREE:"SET_IS_FREE",
}

export default actionTypes